# permissions for end users to view demovolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app-monitoring-crd
    app.kubernetes.io/managed-by: kustomize
  name: demovolume-viewer-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - demovolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - demovolumes/status
  verbs:
  - get
